spintest.out:
	gcc -o spintest.out spintest.c spinlib.c tas.s
semtest.out:
	gcc -o semtest.out semtest.c sem.c spinlib.c tas.s
fifotest.out:
	gcc -o fifotest.out fifotest.c fifo.c sem.c spinlib.c tas.s
acidtest.out:
	gcc -o acidtest.out acidtest.c fifo.c sem.c spinlib.c tas.s
